<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.cru</groupId>
        <artifactId>aws-sdk</artifactId>
        <version>1.0</version>
    </parent>

    <groupId>aws-sdk</groupId>
    <artifactId>core</artifactId>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- AWS dependencies -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>cloudsearch</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>cloudsearchdomain</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>ssm</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>auth</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-core</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>regions</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <version>${bnd.version}</version>
                <executions>
                    <execution>
                        <id>bnd-process</id>
                        <goals>
                            <goal>bnd-process</goal>
                        </goals>
                        <configuration>
                            <bnd><![CDATA[
        Import-Package: javax.annotation;version="[0.0,2)",\
                        software.amazon.awssdk.*,\
                        *
        Export-Package: software.amazon.awssdk.ssm;version=${aws.sdk.version},\
                        software.amazon.awssdk.cloudsearch;version=${aws.sdk.version},\
                        software.amazon.awssdk.auth.credentials;version=${aws.sdk.version},\
                        software.amazon.awssdk.core.client.builder;version=${aws.sdk.version},\
                        software.amazon.awssdk.services.cloudsearchdomain;version=${aws.sdk.version},\
                        software.amazon.awssdk.services.cloudsearchdomain.model;version=${aws.sdk.version},\
                        software.amazon.awssdk.core.sync;version=${aws.sdk.version},\
                        software.amazon.awssdk.regions;version=${aws.sdk.version},\
                        software.amazon.awssdk.awscore.client.builder;version=${aws.sdk.version},\
                        ]]></bnd>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>