<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.cru</groupId>
        <artifactId>aws-sdk</artifactId>
        <version>3.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>aws-sdk.core</artifactId>
    <name>aws-sdk - Core</name>
    <description>AWS SDK bundle for Cru - wraps AWS SDK in an OSGI bundle.</description>

    <build>
        <plugins>
<!--            Sling Maven Plugin-->
            <plugin>
                <groupId>org.apache.sling</groupId>
                <artifactId>sling-maven-plugin</artifactId>
            </plugin>

<!--            Maven Dependency Plugin-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>cloudsearch</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>cloudsearchdomain</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>ssm</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>auth</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>aws-core</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>regions</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>http-client-spi</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>sdk-core</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>identity-spi</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.awssdk</groupId>
                                    <artifactId>utils</artifactId>
                                    <version>${aws.sdk.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>software.amazon.eventstream</groupId>
                                    <artifactId>eventstream</artifactId>
                                    <version>1.0.1</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                            <overWriteReleases>true</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

<!--            Bnd Maven Plugin-->
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bnd-process</id>
                        <goals>
                            <goal>bnd-process</goal>
                        </goals>
                        <configuration>
                            <bnd><![CDATA[
Bundle-Name: awssdk - Core
Bundle-SymbolicName: awssdk.core
Bundle-Description: OSGI version of aws sdk jars
Export-Package: software.*,META-INF.services.*
Import-Package: javax.annotation;version="[0.0,2)",\
                !*
                            ]]></bnd>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

<!--            Bnd Baseline Maven Plugin-->
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-baseline-maven-plugin</artifactId>
                <configuration>
                    <failOnMissing>false</failOnMissing>
                </configuration>
                <executions>
                    <execution>
                        <id>baseline</id>
                        <goals>
                            <goal>baseline</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

<!--            Maven Jar Plugin-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
